---

- name: Install pipewire
  community.general.pacman:
    name: 
          - pipewire
          - pipewire-audio
          - pipewire-alsa
          - pipewire-pulse
          - pipewire-jack
          - pulsemixer
